### ISSUE TITLE
Indentation issues on 0.2.0

### ISSUE THREAD

**Issue by RomLecat** [devopsarr/radarr-py#6]
Hello,

There's an indent issue on the latest release :)
Here's the traceback:

```
Traceback (most recent call last):
  File "/opt/zabbix-tools/./arr_agent.py", line 9, in <module>
    import radarr
  File "/usr/local/lib/python3.9/dist-packages/radarr/__init__.py", line 22, in <module>
    from radarr.api.alternative_title_api import AlternativeTitleApi
  File "/usr/local/lib/python3.9/dist-packages/radarr/api/__init__.py", line 16, in <module>
    from radarr.api.alternative_title_api import AlternativeTitleApi
  File "/usr/local/lib/python3.9/dist-packages/radarr/api/alternative_title_api.py", line 26, in <module>
    from radarr.api_client import ApiClient
  File "/usr/local/lib/python3.9/dist-packages/radarr/api_client.py", line 25, in <module>
    from radarr.configuration import Configuration
  File "/usr/local/lib/python3.9/dist-packages/radarr/configuration.py", line 432
    "SDK Package Version: 0.2.0".\
IndentationError: unexpected indent
```

Thanks

**Comment by Fuochi** [comment]
my bad, I'll slowly put some basic checks to avoid this kind of issues in future. Now this should be fixed across the SDKs

**Comment by RomLecat** [comment]
Thanks, it works perfectly.

As always, thanks a lot for your work and this awesome project!
